config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get "(page/:page)", action: :index, on: :collection, as: ""
  end

  root to: "pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :carts, only: %i(index) do
    collection do
      get "add-to-cart/:id(/:quantity)", to: "carts#add_to_cart",
                                          as: :add_to
      get "minus-item-cart/:id(/:quantity)", to: "carts#minus_quantity_cart",
                                              as: :minus_item
      delete "delete-cart", to: "carts#delete_cart",
                                  as: :delete
      delete "delete-item-cart/:id", to: "carts#delete_item_cart",
                                      as: :destroy_item
    end
  end
  resources :products, only: :index
  resources :orders, only: %i(new create)
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :load_product,
                only: %i(add_to_cart delete_item_cart minus_quantity_cart)
  before_action :sold_out?, :max_quantity, :session_cart, only: %i(add_to_cart)
  before_action :cart_include_product?,
                only: %i(delete_item_cart minus_quantity_cart)

  def index
    store_location
  end

  def add_to_cart
    id = params[:id]
    session_cart.include?(id) ? add_exist_product(id) : add_new_product(id)
  end

  def minus_quantity_cart
    id = params[:id]
    session_cart[id] = session_cart[id].to_i - handle_quantity
    return min_quantity_product_message id if quantity_less_than_one? id

    flash.now[:success] = t :minus_quantity_cart_success
    respond_to do |format|
      format.html{redirect_to carts_path}
      format.js
    end
  end

  def delete_item_cart
    session_cart.delete params[:id]
    return delete_cart if session_cart.count.zero?

    flash.now[:success] = t :delete_item_cart_success
    respond_to do |format|
      format.html{redirect_back_or root_path}
      format.js
    end
  end

  def delete_cart
    session[:cart] = nil
    flash[:success] = t :delete_cart_success
    redirect_to carts_path
  end

  private

  def load_product
    @product = Product.find_by id: params[:id]
    return if @product

    flash[:warning] = t :not_found
    return render(js: "window.location = '#{carts_path}'") if request.xhr?

    redirect_back_or root_path
  end

  def sold_out?
    return unless @product.quantity.zero?

    flash[:warning] = t :sold_out
    redirect_back_or root_path
  end

  def max_quantity
    return if params[:quantity].to_i <= @product.quantity

    flash[:warning] = t :max_quantity
    redirect_back_or root_path
  end

  def add_new_product id
    session_cart[id] = handle_quantity
    return error_handle_add id if quantity_less_than_one? id

    successful_handle_add
  end

  def add_exist_product id
    session_cart[id] = session_cart[id].to_i + handle_quantity
    return error_handle_add id if quantity_less_than_one? id

    successful_handle_add
  end

  def handle_quantity
    params[:quantity].present? ? params[:quantity].to_i : 1
  end

  def successful_handle_add
    flash[:success] = t :add_to_cart_success
    redirect_back_or root_path
  end

  def error_handle_add id
    session_cart[id] = 1
    flash[:error] = t :add_to_cart_error
    redirect_back_or root_path
  end

  def cart_include_product?
    return if session_cart.include? params[:id]

    flash[:warning] = t :cart_not_contain_product
    return render(js: "window.location = '#{carts_path}'") if request.xhr?

    redirect_to carts_path
  end

  def quantity_less_than_one? id
    session_cart[id].to_i < 1
  end

  def min_quantity_product_message id
    session_cart[id] = 1
    flash.now[:warning] = t :min_quantity_product
    respond_to do |format|
      format.html{redirect_to carts_path}
      format.js
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def session_cart
    session[:cart] ||= Hash.new
  end

  def current_cart
    @current_cart ||= session[:cart]
  end

  def session_cart_exist?
    current_cart.present?
  end

  def total_item_cart price, total_quantity_item
    @total_item_cart = price.to_i * total_quantity_item.to_i
  end

  def total_quantity_cart cart
    session_cart_exist? ? cart.count : 0
  end

  def total_price_cart cart
    return 0 unless session_cart_exist?

    cart.reduce(0) do |total, product|
      total + product.price.to_i * session_cart[product.id.to_s].to_i
    end
  end
end

app/views/carts/_cart.html.erb
<% if session_cart_exist? %>
  <table>
    <thead>
      <tr>
        <th><%= t :product_image %></th>
        <th class="p-name"><%= t :product_name %></th>
        <th><%= t :product_price %></th>
        <th><%= t :quantity %></th>
        <th><%= t :total %></th>
        <th>
          <%= link_to delete_carts_path, method: :delete, data: {confirm: t("you_sure")} do %>
            <i class="ti-close"></i>
          <% end %>
        </th>
      </tr>
    </thead>
    <tbody class="all-cart">
      <% @products_load_in_cart.each do |product| %>
        <tr>
          <td class="cart-pic first-row"><img src="/assets/img/cart-page/product-1.jpg" alt=""></td>
          <td class="cart-title first-row">
            <h5><%= product.name %></h5>
          </td>
          <td class="p-price first-row"><%= number_to_currency product.price %></td>
          <td class="qua-col first-row">
            <div class="quantity">
              <div class="cart-quantity-add" style="display: inline-block">
                <%= link_to minus_item_carts_path(product.id), class: "minus-product", remote: true do %>
                  <i class="fa fa-minus"></i>
                <% end %>
                <input data-id="<%= product.id %>" type="number" min="1" class="input-quantity w-50"
                value="<%= session_cart[product.id.to_s] %>" id="<%= session_cart[product.id.to_s] %>">
                <%= link_to add_to_carts_path(product.id), class: "plus-product" do %>
                  <i class="fa fa-plus"></i>
                <% end %>
              </div>
            </div>
          </td>
          <td class="total-price first-row">
            <%= number_to_currency total_item_cart(product.price, session_cart[product.id.to_s]) %>
          </td>
          <td class="si-close first-row">
            <%= link_to destroy_item_carts_path(product.id), method: :delete, data: {confirm: "You sure?", remote: true} do %>
              <i class="ti-close"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h1><%= t :cart_empty %></h1>
<% end %>

<%= javascript_pack_tag "handle-ajax-cart" %>

app/views/carts/_handle_ajax.js.erb
<%= sanitize toastr_flash %>
$('.cart-table').html('<%= j render "carts/cart" %>');
$('.cart-icon').html('<%= j render "layouts/cart" %>');
$('.cart-price').html('<%= number_to_currency total_price_cart(@products_load_in_cart) %>');
$('.cart-total').html('<span><%= number_to_currency total_price_cart(@products_load_in_cart) %></span>');

app/views/carts/delete_item_cart.js.erb
<%= render "handle_ajax" %>

app/views/carts/index.html.erb
<% provide :title, t(".cart") %>
<% provide :breadcrumb, t(".cart") %>
<%= render "commons/breadcrumb" %>

<!-- Shopping Cart Section Begin -->
<section class="shopping-cart spad">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="cart-table">
          <%= render "cart" %>
        </div>
        <div class="row">
          <div class="col-lg-4">
            <div class="cart-buttons">
              <%= link_to  t("continue_shopping"), root_path, class: "primary-btn continue-shop" %>
            </div>
          </div>
          <div class="col-lg-4 offset-lg-4">
            <div class="proceed-checkout">
              <ul>
                <li class="cart-total">Total 
                  <span><%= number_to_currency total_price_cart(@products_load_in_cart) %></span>
                </li>
              </ul>
              <% if logged_in? %>
                <%= link_to t("check_out"), new_order_path, class: "proceed-btn" %>
              <% else %>
                <%= link_to t("log_in"), login_path, class: "proceed-btn" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Shopping Cart Section End -->

app/views/carts/minus_quantity_cart.js.erb
<%= render "handle_ajax" %>