config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get "(page/:page)", action: :index, on: :collection, as: ""
  end

  root to: "pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :carts, only: %i(index) do
    collection do
      get "add-to-cart/:id(/:quantity)", to: "carts#add_to_cart",
                                          as: :add_to
      get "minus-item-cart/:id(/:quantity)", to: "carts#minus_quantity_cart",
                                              as: :minus_item
      delete "delete-cart", to: "carts#delete_cart",
                                  as: :delete
      delete "delete-item-cart/:id", to: "carts#delete_item_cart",
                                      as: :destroy_item
    end
  end
  resources :products, only: :index
  resources :orders, only: %i(new create)
end

app/views/layouts/_cart.html.erb
<a href="#">
  <i class="icon_bag_alt"></i>
  <span><%= total_quantity_cart @products_load_in_cart %></span>
</a>
<div class="cart-hover">
  <div class="select-items">
    <table>
      <tbody>
        <% if session_cart_exist? %>
          <% @products_load_in_cart.take(3).each do |product| %>
            <tr>
              <td class="si-pic"><img src="/assets/img/select-product-1.jpg" alt=""></td>
              <td class="si-text">
                <div class="product-selected">
                  <p><%= number_to_currency product.price %> x <%= session_cart[product.id.to_s] %></p>
                  <h6><%= product.name %></h6>
                </div>
              </td>
              <td class="si-close">
                <%= link_to destroy_item_carts_path(product.id), method: :delete, data: {confirm: "You sure?", remote: true} do %>
                  <i class="ti-close"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td class="si-text">
              <div class="product-selected">
                <p><%= t :no_have_product %></p>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="select-total">
    <span><%= t :total_cart %></span>
    <h5><%= number_to_currency total_price_cart(@products_load_in_cart) %></h5>
  </div>
  <div class="select-button">
    <%= link_to t("header.view_cart"), carts_path, class: "primary-btn view-card" %>
    <% if logged_in? %>
      <%= link_to t("header.check_out"), new_order_path, class: "primary-btn checkout-btn" %>
    <% else %>
      <%= link_to t("sessions.new.log_in"), login_path, class: "primary-btn checkout-btn" %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer Section Begin -->
<footer class="footer-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-3">
        <div class="footer-left">
          <div class="footer-logo">
            <a href="#"><img src="/assets/img/footer-logo.png" alt=""></a>
          </div>
          <ul>
            <li>43a Lorem Igsume, London</li>
            <li>+65 11.188.888</li>
            <li>hello.colorlib@gmail.com</li>
          </ul>
          <div class="footer-social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-instagram"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-pinterest"></i></a>
          </div>
        </div>
      </div>
      <div class="col-lg-2 offset-lg-1">
        <div class="footer-widget">
          <h5><%= t :no_link %></h5>
          <ul>
            <li><a href="#"><%= t :no_link %></a></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-2">
        <div class="footer-widget">
          <h5><%= t :no_link %></h5>
          <ul>
            <li><a href="#"><%= t :no_link %></a></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="newslatter-item">
          <h5><%= t :no_link %></h5>
          <p><%= t :join_us %></p>
          <form action="#" class="subscribe-form">
            <input type="text" placeholder="Enter Your Mail">
            <button type="button"><%= t :no_link %></button>
          </form>
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- Footer Section End -->

app/views/layouts/_header.html.erb
<!-- Header Section Begin -->
<header class="header-section">
  <div class="header-top">
    <div class="container">
      <div class="ht-left">
        <div class="mail-service">
          <i class=" fa fa-envelope"></i>
          <%= t :email_contact %>
        </div>
        <div class="phone-service">
          <i class=" fa fa-phone"></i>
          <%= t :number_phone %>
        </div>
      </div>
      <div class="ht-right">
        <a href="#" class="login-panel"><i class="fa fa-user"></i></a>
        <div class="lan-selector">
          <select class="language_drop" name="countries" id="countries">
            <option value="yt" data-image="/assets/img/flag-1.jpg" data-imagecss="flag yt"
              data-title="English"><%= link_to t("header.en"), locale: :en %></option>
            <option value="yu" data-image="/assets/img/flag-2.jpg" data-imagecss="flag yu"
              data-title="Vietnamese"><%= link_to t("header.vi"), locale: :vi %></option>
          </select>
        </div>
        <div class="top-social">
          <a href="#"><i class="ti-facebook"></i></a>
          <a href="#"><i class="ti-twitter-alt"></i></a>
          <a href="#"><i class="ti-linkedin"></i></a>
          <a href="#"><i class="ti-pinterest"></i></a>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="inner-header">
      <div class="row">
        <div class="col-lg-2 col-md-2">
          <div class="logo">
            <a href="./index.html">
            <img src="/assets/img/logo.png" alt="">
            </a>
          </div>
        </div>
        <div class="col-lg-7 col-md-7">
          <div class="advanced-search">
            <button type="button" class="category-btn"><%= t :all_category %></button>
            <div class="input-group">
              <input type="text" placeholder="<%= t :search %>">
              <button type="button"><i class="ti-search"></i></button>
            </div>
          </div>
        </div>
        <div class="col-lg-3 text-right col-md-3">
          <ul class="nav-right">
            <li class="heart-icon">
              <a href="#">
              <i class="icon_heart_alt"></i>
              <span>1</span>
              </a>
            </li>
            <li class="cart-icon">
              <%= render "layouts/cart" %>
            </li>
            <li class="cart-price"><%= number_to_currency total_price_cart @products_load_in_cart %></li>
            <% if logged_in? %>
              <li class="dropdown">
                <%= link_to "#", class: "dropdown-toggle login-header", "data-toggle": "dropdown", "aria-expanded": "true" do %>
                  <%= content_tag(:i, "", class: "fa fa-user")%>
                <% end %>
                <ul class="dropdown-menu">
                  <li><%= link_to t("header.profile"), "#" %></li>
                  <li><%= link_to t("header.setting"), "#" %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to t("header.log_out"), logout_path, method: :delete %>
                  </li>
                </ul>
              </li>
              <li>
                <%= button_to logout_path, method: :delete do %>
                  <%= content_tag(:i, "", class: "fa fa-sign-out")%>
                  <%= t "Logout" %>
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to login_path, class: "login-header" do %>
                  <%= content_tag(:i, "", class: "fa fa-user")%>
                  <%= t "sessions.new.login" %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="nav-item">
    <div class="container">
      <div class="nav-depart">
        <div class="depart-btn">
          <i class="ti-menu"></i>
          <span><%= t :all_departments %></span>
          <ul class="depart-hover">
            <li class="active"><a href="#"><%= t :no_link %></a></li>
          </ul>
        </div>
      </div>
      <nav class="nav-menu mobile-menu">
        <ul>
          <li class="active"><%= link_to t("application.home"), root_path %></li>
          <li><%= link_to t("product.shop"), products_path %></li>
          <li>
            <a href="#"><%= t :no_link %></a>
            <ul class="dropdown">
              <li><a href="#"><%= t :no_link %></a></li>
            </ul>
          </li>
          <li><a href="./blog.html"><%= t :no_link %></a></li>
          <li><a href="./contact.html"><%= t :no_link %></a></li>
          <li>
            <a href="#"><%= t :no_link %></a>
            <ul class="dropdown">
              <li><a href="./blog-details.html"><%= t :no_link %></a></li>
              <li><a href="./shopping-cart.html"><%= t :no_link %></a></li>
              <li><a href="./check-out.html"><%= t :no_link %></a></li>
            </ul>
          </li>
          <li>
            <a href="./blog.html"><%= t "header.language" %></a>
            <ul class="dropdown">
              <li><%= link_to t("eng"), locale: :en %></li>
              <li><%= link_to t("vnese") , locale: :vi %></li>
            </ul>
          </li>
        </ul>
      </nav>
      <div id="mobile-menu-wrap"></div>
    </div>
  </div>
</header>
<!-- Header End -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="/assets/bootstrap-dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/assets/themify-icons-font/themify-icons/themify-icons.css" type="text/css">
    <link rel="stylesheet" href="/assets/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="/assets/OwlCarousel2-2.3.4/dist/assets/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="/assets/jquery-nice-select-1.1.0/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="/assets/jquery-ui-1.12.1/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="/assets/SlickNav-master/dist/slicknav.min.css" type="text/css">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <%= render "layouts/header" %>

    <div>
      <%= yield %>
    </div>

    <!-- Debug
    <%= debug(params) if Rails.env.development? %>
    -->
    <%= render "layouts/footer" %>

    <!-- Js Plugins -->
    <script src="/assets/jquery-3.3.1.min.js"></script>
    <script src="/assets/jquery-ui-1.12.1/jquery-ui.min.js"></script>
    <script src="/assets/jQuery.countdown/dist/jquery.countdown.min.js"></script>
    <script src="/assets/jquery-nice-select-1.1.0/js/jquery.nice-select.min.js"></script>
    <script src="/assets/zoom-master/jquery.zoom.min.js"></script>
    <script src="/assets/jquery.dd.min.js"></script>
    <script src="/assets/jquery.slicknav.js"></script>
    <script src="/assets/OwlCarousel2-2.3.4/dist/owl.carousel.min.js"></script>
    <script src="/assets/main.js"></script>
    <script><%= sanitize toastr_flash %></script>
    <%= javascript_pack_tag "custom", "data-turbolinks-track": "reload" %>
  </body>
</html>